### ISSUE TITLE
[Question]: Set branding via Actions derive

### ISSUE THREAD

**Issue by Caellian** [42ByteLabs/ghactions#131]
I tried using:

```rust
#[derive(Actions, Debug, Clone)]
#[action(
    name = "...",
    description = "...",
    icon = "tag",
    color = "orange",
    path = "./action.yml",
    image = "./Dockerfile"
)]
pub struct Action {}
```

as well as:

```rust
#[derive(Actions, Debug, Clone)]
#[action(
    name = "...",
    description = "...",
    branding = {
        icon = "tag",
        color = "orange"
    },
    path = "./action.yml",
    image = "./Dockerfile"
)]
pub struct Action {}
```

and some other combinations but can't seem to figure out how to set `icon` and `color` fields. It's also not documented anywhere yet.

**Comment by GeekMasher** [comment]
@Caellian Sorry for the delay.

Thanks for raising this. Currently this isn't supported but I can absolutely add support for this soon.

**Comment by GeekMasher** [comment]
Closing as resolved, please check the code/docs for more info
